integration-tests/other: Add missing include
This fixes that clang-16 fails with this error:

    src/coverage/crashing_fuzz_test.c:29:7: error: call to undeclared library function 'exit' with type 'void (int) __attribute__((noreturn))'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          exit(1);
          ^
    src/coverage/crashing_fuzz_test.c:29:7: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'