docs(bazel): add python and bazel dependencies to docs.
Python is a dependency of the `rules_fuzzing` package (bazel) and needs to be installed on the users system.
On a minimal Arch install, python is not necessarily installed, so we mention it as a dependency.

The following error message will appear otherwise:

    Error in fail: python interpreter `None` not found in PATH
    ERROR: /__w/cifuzz/cifuzz/examples/bazel/src/BUILD.bazel:10:13: //src:explore_me_fuzz_test_corpus depends on @rules_fuzzing//fuzzing/tools:make_corpus_dir in repository @rules_fuzzing which failed to fetch. no such package '@fuzzing_py_deps//': python interpreter `None` not found in PATH

 - also add Windows section according to e2e pipeline
 - python is required for bazel and is not necessarily installed on
   Arch.